# This is a basic workflow to help you get started with Actions

name: RELEASE

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate:
    name: Build
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [macos-latest, ubuntu-latest, windows-latest]
        ocaml-version: [ '4.6.1000' ]
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - name: Install esy
      run: npm install -g esy
    - name: Override esy version
      uses: giltho/esy-override-action@v0.0.3
    - name: Esy install
      run: esy install
    - name: Esy build
      run: esy build
      with:
        ocaml-version: ${{ matrix.ocaml-version }}
    - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        with:
          args: 'example-*'
